name: Build, Push & Deploy All Services

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate service list
        id: set-matrix
        run: |
          services=$(ls services)
          # convert to JSON array for matrix
          json_matrix="{\"service\":[\"$(echo $services | sed 's/ /\",\"/g')\"]}"
          echo "Matrix: $json_matrix"
          # write to environment file for outputs
          echo "matrix=$json_matrix" >> $GITHUB_OUTPUT

  build-and-push:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push ${{ matrix.service }}
        uses: docker/build-push-action@v6
        with:
          context: ./services/${{ matrix.service }}
          file: ./services/${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mp3_${{ matrix.service }}:${{ github.sha }}

  trigger-render-deploys:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploys
        run: |
          echo '${{ secrets.RENDER_SERVICE_IDS }}' > services.json
          for service in $(jq -r 'keys[]' services.json); do
            SERVICE_ID=$(jq -r ".\"$service\"" services.json)
            IMAGE_URL="docker.io/${{ secrets.DOCKERHUB_USERNAME }}/mp3_${service}:${{ github.sha }}"
            echo "Triggering deploy for $service -> $SERVICE_ID with image $IMAGE_URL"
            curl -X POST "https://api.render.com/v1/services/$SERVICE_ID/deploys" \
                 -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
                 -H "Content-Type: application/json" \
                 -d "{\"imageUrl\":\"$IMAGE_URL\"}"
          done
